// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1tKpI8-E77OclJG8a4s-a1msqlh3p4MU',
    appId: '1:729418199644:web:416234d4f7d77ab40b6c99',
    messagingSenderId: '729418199644',
    projectId: 'evminute-519e3',
    authDomain: 'evminute-519e3.firebaseapp.com',
    storageBucket: 'evminute-519e3.appspot.com',
    measurementId: 'G-2XPPF7XB9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCmDyqmbhbT8oaRoEBleCxQAND3dyx3Y',
    appId: '1:729418199644:android:c6b68ded3890ae120b6c99',
    messagingSenderId: '729418199644',
    projectId: 'evminute-519e3',
    storageBucket: 'evminute-519e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcolxqu3lGfKdT9DyZg2LigbmKefRlFbc',
    appId: '1:729418199644:ios:9a24415bf9bf46d40b6c99',
    messagingSenderId: '729418199644',
    projectId: 'evminute-519e3',
    storageBucket: 'evminute-519e3.appspot.com',
    androidClientId: '729418199644-ekksb15a6pesnjed2clip6uakp6sle4r.apps.googleusercontent.com',
    iosClientId: '729418199644-7mlc9puvaomai3uajnhdlpv30hu6cmoi.apps.googleusercontent.com',
    iosBundleId: 'imps.evminute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcolxqu3lGfKdT9DyZg2LigbmKefRlFbc',
    appId: '1:729418199644:ios:b4e66942dbdd972e0b6c99',
    messagingSenderId: '729418199644',
    projectId: 'evminute-519e3',
    storageBucket: 'evminute-519e3.appspot.com',
    androidClientId: '729418199644-ekksb15a6pesnjed2clip6uakp6sle4r.apps.googleusercontent.com',
    iosClientId: '729418199644-bmkjrli8rrf7ssv9e2dvstc7vpim2oc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.evminute.RunnerTests',
  );
}
